# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

name: $(Major).$(Minor).$(Rev:r)

variables:
  Major: 1
  Minor: 0
  buildConfiguration: 'Release'

steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '57d1ab88-427d-408d-a04b-a138fa7875f5'

#- task: DotNetCoreCLI@2
#  displayName: 'dotnet pack'
#  inputs:
#    command: 'pack'
#    packagesToPack: '**/*.csproj'
#    versioningScheme: 'byPrereleaseNumber'
#    majorVersion: '1'
#    minorVersion: '0'
#    patchVersion: '0'



- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byBuildNumber'
#    packDirectory: '$(Build.ArtifactStagingDirectory)/packages/releases'
#    arguments: '--configuration $(buildConfiguration)'
#    nobuild: true



- task: PublishBuildArtifacts@1
  displayName: 'publish build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DotNetCoreCLI@2
  displayName: 'dotnet nuget push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '57d1ab88-427d-408d-a04b-a138fa7875f5'